### ISSUE TITLE
PIDパラメータを調整する (R)

### ISSUE THREAD

**Issue by shigyo123** [KatLab-MiyazakiUniv/etrobocon2020#23]
## 完了条件
- 区間ごとにパラメータを調整する
- 完走する
- 目標タイム内にゴールする

**Comment by shigyo123** [comment]
走行タイムを動画にしました。
https://photos.app.goo.gl/U2QBXjBN3eDEciVu9

**Comment by Takahiro55555** [comment]
![LGTM](https://cdn.lgtmoon.dev/images/94059)
