### ISSUE TITLE
カーブの曲率を  計測・計算する(LR)

### ISSUE THREAD

**Issue by mutotaka0426** [KatLab-MiyazakiUniv/etrobocon2020#27]
## 完了条件
- コースからカーブを計測して曲率・曲率半径を算出する
- LとRの両コースで算出する
- 算出された値をPIDパラメータの調整担当者に渡す

**Comment by sugaken0528** [comment]
good job

**Comment by arimakaoru** [comment]
![LGTM](https://cdn.lgtmoon.dev/images/93267)
