### ISSUE TITLE
コースを区間分割・計算する（LR）

### ISSUE THREAD

**Issue by Takahiro55555** [KatLab-MiyazakiUniv/etrobocon2020#28]
## 完了条件
- コースを区間分割する
- 各区間の長さやカーブの半径を計測する
- 上記の分割・計測結果をドキュメントにまとめる

## 計測方法
- コースを印刷してメジャーなどで直接計測する
- 画像を何らかのソフトウェアで読みこんで計測する（Fusion360などのCADソフトを想定）
- シュミレータ上でロボットを動かして計測する（専用プログラムを作成）

自分は、2番目の方法で計測予定

## 関連資料（省略可）
GoogleDriveにあるコース資料

**Comment by arimakaoru** [comment]
Approve!!

**Comment by sugaken0528** [comment]
good job
