### ISSUE TITLE
Fork先のリポジトリで GitHub Actions が動くようにするための方法を Wiki に書く

### ISSUE THREAD

**Issue by Takahiro55555** [KatLab-MiyazakiUniv/etrobocon2020#31]
## 完了条件
- Fork 先のリポジトリで GitHub Actions が動くようにするための方法を Wiki に書く
- 複数人で動作確認を行う（2人以上）

## 関連資料（省略可）
現時点での手順

> 1. リポジトリを Fork して Clone
> 2. Fork したリポジトリの Webページから GitHub Actions を有効化する
> 3. `.github/workflows/google-test.yaml` ファイルの末尾の改行を増やして Commit & Push（ファイルに適当な変更を加える）
>
> ```
> echo "" >> .github/workflows/google-test.yaml
> git add .github/workflows/google-test.yaml
> git commit -m "tmp: GitHub Actions の workflow を走らせたい..."
> git push origin master
> ```
> 
> 4.  `.github/workflows/google-test.yaml` ファイルの上記の Commit を取り消して Push
> `git reset --hard HEAD^`
> `git push origin master -f`
> 5.  Fork したリポジトリの Webページから GitHub Actions が走っていることを確認する。今回の場合、計2回走っているはず...
> 6.  以降は、Push 時に GitHub Actions が走ってくれるはず...

**Comment by Takahiro55555** [comment]
以下のリンクから確認することができます

[Fork先のリポジトリでGitHubActionsのワークフローを有効化する方法
](https://github.com/KatLab-MiyazakiUniv/etrobocon2020/wiki/Fork%E5%85%88%E3%81%AE%E3%83%AA%E3%83%9D%E3%82%B8%E3%83%88%E3%83%AA%E3%81%A7GitHubActions%E3%81%AE%E3%83%AF%E3%83%BC%E3%82%AF%E3%83%95%E3%83%AD%E3%83%BC%E3%82%92%E6%9C%89%E5%8A%B9%E5%8C%96%E3%81%99%E3%82%8B%E6%96%B9%E6%B3%95)

**Comment by arimakaoru** [comment]
Approve!!
![LGTM](https://cdn.lgtmoon.dev/images/94071)

**Comment by sugaken0528** [comment]
good job
